### ISSUE TITLE
FastQC and Trimming?

### ISSUE THREAD

**Issue by dmncyap** [erilu/bulk-rnaseq-analysis#1]
Hi! I noticed that trimming is not part of your RNASeq pipeline. Would you still do quality checks and trimming when analyzing RNASeq datasets that you didn't have sequenced yourself?

**Comment by erilu** [comment]
Hi dmncyap,

Thanks for your question about FastQC and trimming. Yes, it is always a good idea to run FastQC on your fastq files to look at the overall quality of the data, especially on datasets that you didn't sequence yourself.

Nowadays sequencing facilities will usually run FastQC for you and provide you the QC report along with your fastq files. Trimming can be done using tools such as cutadapt if necessary, but in some cases STAR is able to align reads accurately without trimming.

In addition to doing those quality checks, I also recommend trying to reproduce the findings from the paper the data was associated with to confirm that you have correctly processed the data, before using it to make new conclusions.

Best,
Erick
